version: "3.8"
services:
  docker-database-service:
    restart: always
    build:
      context: ./DOCKER_DATABASE
    container_name: composed-docker-database
    ports:
      - "5455:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_docker_ass_database
  
  docker-backend-service:
    build:
      context: ./DOCKER_BACKEND
      
    container_name: composed-docker-backend

    ports:
      - "8080:8080"

    depends_on:
      - docker-database-service
    
    environment:
      - spring.datasource.url=jdbc:postgresql://host.docker.internal:5455/my_docker_ass_database
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.application.name=doc-ass
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.jpa.hibernate.ddl-auto=update
    
  docker-frontend-service:
    build:
      context: ./DOCKER_FRONTEND/my-app

    ports:
      - "3000:3000"

    container_name: composed-docker-frontend





