apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: docker-database-service
  name: docker-database-service
spec:
  ports:
    - name: "5455"
      port: 5455
      targetPort: 5432
  selector:
    io.kompose.service: docker-database-service
